ECHO OFF
CLS
:MENU
ECHO.
ECHO ..................................................................
ECHO PRESS 1 OR 2 OR 3 OR 4 OR 5 OR 6 OR 7 TO SELECT YOU TASK, OR 8 TO EXIT.
ECHO ..................................................................
ECHO.
ECHO 1 - DELETE COOKIES
ECHO 2 - DELETE RECENT DOCUMENTS LIST
ECHO 3 - DELETE MY TEMP
ECHO 4 - DELETE MY TEMP INTERNET FILES
ECHO 5 - DELETE SYSTEM TEMP
ECHO 6 - DELETE RECYCLE BIN
ECHO 7 - CLEAR ALL
ECHO 8 - EXIT
ECHO.
SET /P M=TYPE 1,2,3,4,5,6,7 OR 8 THEN PRESS ENTER:
IF%M%==1 GOTO DELETE COOKIES
IF%M%==2 GOTO RECENT DOCUMENTS LIST
IF%M%==3 GOTO MY TEMP
IF%M%==4 GOTO MY TEMP INTERNET FILES
IF%M%==5 GOTO SYSTEM TEMP
IF%M%==6 GOTO RECYCLE BIN
IF%M%==7 GOTO 
IF%M%==8 GOTO EXIT
:DELETE COOKIES
del /F /S /Q C:\docume~1\%USERNAME%\COOKIES\*.*
GOTOMENU
:RECENT DOCUMENTS LIST
del /F /S /Q C:\docume~1\%USERNAME%\recent\*.*
GOTOMENU
:MY TEMP
del /F /S /Q C:\docume~1\%USERNAME%\locals~1\temp\*.*
GOTOMENU
:MY TEMP INTERNET FILES
del /F /S /Q C:\docume~1\%USERNAME%\locals~1\Temport~1\*.*
GOTOMENU
:SYSTEM TEMP
del /F /S /Q %SystemRoot%\temp\*.*
GOTOMENU
:RECYCLE BIN
del /F /S /Q C:\recycler\*.*
GOTOMENU
: